version: "3"

services:
  node:
    build: ./backend
    depends_on:
      - sql
    env_file:
      # Make sure to update this to match your project.
      - ./project.env
    environment:
      - MYSQL_HOST=sql
    ports:
      - 8080:4200
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  sql:
    build: ./sql
    # Make sure to update this to match your project.
    env_file:
      - ./project.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - compose-lesson:/var/lib/mysql
    ports:
      - 33006:3306
volumes:
  compose-lesson: